name: "unet"
platform: "tensorrt_plan"
max_batch_size: 8

input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 256, 256]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [49, 256, 256]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [ 1 ]
  }
]
