version: '3.9'

services:
  triton-dev:
    image: nvcr.io/nvidia/tritonserver:25.06-py3
    volumes:
      - ./model_repository/hunyuan3d:/models/hunyuan3d
    ports:
      - 1234:8000
      - 1235:8001
      - 1236:8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["tail", "-f", "/dev/null"]

  stablediffusion:
    build:
      context: ./dockerfiles
      dockerfile: StableDiffusion.Dockerfile
    volumes:
      - ./model_repository/stable_diffusion:/models/stable_diffusion
    ports:
      - 1234:8000
      - 1235:8001
      - 1236:8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["tritonserver", "--model-repository=/models"]

  hunyuan3d:
    build:
      context: ./dockerfiles
      dockerfile: Hunyuan3D.Dockerfile
    volumes:
      - ./model_repository/hunyuan3d:/models/hunyuan3d
    ports:
      - 1237:8000
      - 1238:8001
      - 1239:8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [gpu]
